basePath: /
definitions:
  order.Order:
    properties:
      createdAt:
        type: string
      id:
        type: string
      status:
        type: string
      totalAmount:
        type: number
    type: object
host: localhost:8080
info:
  contact: {}
  description: Fast Food API for FIAP Tech course
  title: Tech Challenge Food API
  version: 0.1.0
paths:
  /order/:id:
    get:
      consumes:
      - application/json
      description: Get order by ID
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/order.Order'
      summary: Get order by ID
      tags:
      - order Routes
swagger: "2.0"
